In [2]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tuple-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [23]:
def create_array(size=(2,2)):
    return np.zeros(size, dtype=int)

print(create_array())

[[0 0]
 [0 0]]


In [29]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlóját feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [ ]:
def set_one(arr):
    np.fill_diagonal(arr, 1)
    return arr

In [ ]:
# Készíts egy függvényt ami transzponálja a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [31]:
def do_transpose(matrix):
    return np.transpose(matrix)

array([[1, 3],
       [2, 4]])

In [ ]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, ha nincs megadva ez a paraméter, akkor legyen az alapértelmezett a kettő 
# Be: [0.1223, 0.1675], 
# Ki: [0.12, 0.17]
# round_array()

In [32]:
def round_array(array, N=2):
    return np.around(array, decimals=N)

array([0.12, 0.17])

In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 0 - False-ra, az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [33]:

def bool_array(array):
    return array.astype(bool)

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
# Készíts egy olyan függvényt, ami a bementként kapott 0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [37]:
def invert_bool_array(arr:np.array) -> np.array:
    bool_arr = np.array(arr, dtype=bool)
    return np.logical_not(bool_arr)

array([[False,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()


In [ ]:
def flatten(array: np.array) -> np.array:
    return np.array(array).flatten()